const GET_REQUEST = "GET_REQUEST";
const GET_SUCCESS = "GET_SUCCESS";
const GET_FAIL = "GET_FAIL";
const USER_SIGNIN = "USER_SIGNIN";
const USER_SIGNOUT = "USER_SIGNOUT";
const PRODUCT_ADD_TO_CART = "PRODUCT_ADD_TO_CART";
const PRODUCT_REMOVE_FROM_CART = "PRODUCT_REMOVE_FROM_CART";
const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";
const CLEAR_CART = "CLEAR_CART";

export {
  GET_FAIL,
  GET_SUCCESS,
  GET_REQUEST,
  USER_SIGNIN,
  USER_SIGNOUT,
  PRODUCT_ADD_TO_CART,
  PRODUCT_REMOVE_FROM_CART,
  SAVE_SHIPPING_ADDRESS,
  SAVE_PAYMENT_METHOD,
  CLEAR_CART
};
